### ISSUE TITLE
Improve error handling for external services

### ISSUE THREAD

**Issue by mpadge** [ropensci-org/buffy#59]
@xuanxu Two questions on different parts of current `external_service_worker`:

1. Current code appears to expect services to always deliver responses, and so will fail if a service is unavailable, right? These lines expect the `response` to be delivered:
https://github.com/ropensci-org/buffy/blob/d42327df027bcdf6dabe4536958cdbc01a2fabd2/app/workers/external_service_worker.rb#L29-L34
but if the service is unavailable, then they will fail. What happens then? More specifically, our main external service rebuilds weekly and so goes off line for around 1 hour or so. Any calls during this time will not return `response` values. It'd be good to be able to deliver informative messages in those cases to say, "please try again in an hour or two".

---

2. Separate but related: Responding the same to all error codes (400-599) is a little too generic. We could at least benefit from informed responses to internal errors from our external service which return 500. Would it be possible instead of this line:
https://github.com/ropensci-org/buffy/blob/d42327df027bcdf6dabe4536958cdbc01a2fabd2/app/workers/external_service_worker.rb#L62
to return the actual HTML error content (so for the 500 example, "Internal server error", rather than "service is currently unavailable")?

---

Thanks!

**Comment by xuanxu** [comment]
> 1 ... if the service is unavailable, then they will fail. What happens then? 

As long as there are any HTTP code responded from the server, that response object will be created. If the external service is rebuilding, I guess the server will reply an error 500, so this will be captured and the default error message will be sent to the github issue.

> It'd be good to be able to deliver informative messages in those cases to say, "please try again in an hour or two".

The message [can be configured](https://buffy-ropensci.readthedocs.io/en/latest/responders/external_service.html#params) using the `:error_msg` parameter in the config file.

> 2 Would it be possible to return the actual HTML error content?

Currently the error message includes the HTTP code, so for a 500 response is "Error 500. The service is currently unavailable", and for a Page Not Found is "Error 404. The service is currently unavailable". The HTML error content is not included right now because it is not guaranteed to be included in every response and could be too technical or misleading for the participants (author/reviewers) in the issue (for instance a "Error 405 Method Not Allowed. The service is currently unavailable" can be confusing for a reviewer). If the error code is not enough I guess the best option is to customize the error message with the `error_msg` param.

**Comment by mpadge** [comment]
Thanks @xuanxu, i'm happy to close this now
